# Generated by Django 4.2 on 2023-04-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='mark',
        ),
    ]
