# Generated by Django 4.2 on 2023-04-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_relation_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='child_id',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='skill',
        ),
        migrations.AddField(
            model_name='relation',
            name='child',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='roadmap.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='roadmap.skill'),
            preserve_default=False,
        ),
    ]
