# Generated by Django 4.2 on 2023-04-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_skill_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='information_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип информации'),
        ),
    ]
