# Generated by Django 4.2 on 2023-04-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_skill_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learned',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='learned',
            name='average',
        ),
        migrations.RemoveField(
            model_name='learned',
            name='beginner',
        ),
        migrations.AddField(
            model_name='learned',
            name='level',
            field=models.CharField(blank=True, max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmap.learned', verbose_name='Уровень изучения'),
        ),
    ]
